sglang/test/nightly/ascend/llm_models/test_ascend_llama_2_7b.py
sglang/test/nightly/ascend/llm_models/test_ascend_baichuan2_13b_chat.py
sglang/test/nightly/ascend/llm_models/test_ascend_glm4_9b_chat.py
sglang/test/nightly/ascend/llm_models/test_ascend_mimo_7b_rl.py
sglang/test/nightly/ascend/llm_models/test_ascend_persimmon_8b_chat.py
sglang/test/nightly/ascend/llm_models/test_ascend_mistral_7b.py
sglang/test/nightly/ascend/llm_models/test_ascend_gemma_3_1b_it.py
sglang/test/nightly/ascend/llm_models/test_ascend_granite_3_0_3b_a800m.py
sglang/test/nightly/ascend/llm_models/test_ascend_internlm2_7b.py
sglang/test/nightly/ascend/llm_models/test_ascend_ling_lite.py
sglang/test/nightly/ascend/llm_models/test_ascend_afm_4_5b.py
sglang/test/nightly/ascend/llm_models/test_ascend_charglm2_6b.py
sglang/test/nightly/ascend/llm_models/test_ascend_exaone_3.py
sglang/test/nightly/ascend/llm_models/test_ascend_phi_4_multimodal.py
sglang/test/nightly/ascend/llm_models/test_ascend_smollm_1_7b.py
sglang/test/nightly/ascend/llm_models/test_ascend_c4ai_command_r_v01.py
sglang/test/nightly/ascend/llm_models/
sglang/test/nightly/ascend/llm_models/
sglang/test/nightly/ascend/llm_models/
sglang/test/nightly/ascend/llm_models/
sglang/test/nightly/ascend/llm_models/
sglang/test/nightly/ascend/llm_models/
sglang/test/nightly/ascend/llm_models/
